function simPlayer(p){return p.type==='custom'?effective(p,career.age,conditionFor(p)):p}
function matchupNotes(a,b){let n=[];const pd=POS_NUM[b.pos]-POS_NUM[a.pos],hd=(b.h||198)-(a.h||198),wd=(b.w||96)-(a.w||96);if(hd>=12)n.push(`${b.name}高出接近${hd}cm，护筐和篮板覆盖会明显改变${a.name}的出手角度。`);if(hd<=-12)n.push(`${a.name}拥有明显身高优势，可以更大胆地在近筐出手和抢二次篮板。`);if(wd>=18)n.push(`${b.name}体重大出一档，${a.name}一旦被压到低位会很难顶住。`);if(pd>=2)n.push(`${a.name}面对更大的${b.pos}：速度和外线更容易制造空间，但篮下对抗吃亏。`);if(pd<=-2)n.push(`${a.name}体型更大：背身和篮板更占便宜，但必须防住换向和外拉。`);if(a.a.three-b.a.perimeter>10)n.push(`${a.name}的外线火力明显超过对方外防，三分会成为主要解法。`);if(a.a.strength-b.a.strength>12)n.push(`${a.name}力量优势明显，会更频繁坐打。`);if(a.a.speed-b.a.speed>12)n.push(`${a.name}第一步优势明显，突破频率会上升。`);return n.slice(0,3)}
function gameWinProb(a,b){const ao=streetOVR(a),bo=streetOVR(b);let edge=(ao-bo)*.027;const pd=POS_NUM[b.pos]-POS_NUM[a.pos];if(pd>=2)edge+=(a.a.speed-b.a.speed)*.006-(b.a.strength-a.a.strength)*.004;if(pd<=-2)edge+=(a.a.strength-b.a.strength)*.005-(b.a.speed-a.a.speed)*.005;edge+=(a.a.three-b.a.perimeter)*.0025+(a.a.finish-b.a.interior)*.0018;return clamp(.5+edge,.16,.84)}
function simulateGame(pa,pb,seed,important=false){
 const r=RNG(seed),a=simPlayer(pa),b=simPlayer(pb),persA=PERSONALITIES[a.personality||a.p]||PERSONALITIES.duncan,persB=PERSONALITIES[b.personality||b.p]||PERSONALITIES.duncan;let sa=0,sb=0,poss=r()<.5?0:1,log=[],posterDone=false,limit=11;
 for(let turn=0;turn<80&&Math.max(sa,sb)<limit;turn++){const atk=poss===0?a:b,def=poss===0?b:a,ap=PERSONALITIES[atk.personality||atk.p]||PERSONALITIES.duncan;let drive=(atk.a.finish+atk.a.dunk+atk.a.speed+atk.a.strength*.45)/3.45,shoot=(atk.a.three*1.1+atk.a.handle*.35)/1.45,mid=(atk.a.mid+atk.a.handle*.28)/1.28;const pd=POS_NUM[def.pos]-POS_NUM[atk.pos],hd=(def.h||198)-(atk.h||198),wd=(def.w||96)-(atk.w||96);if(pd>=2){shoot+=5;drive+=atk.a.speed>def.a.speed?5:-3}if(pd<=-2){drive+=atk.a.strength>def.a.strength?6:-2;shoot-=2}if(hd>10){shoot+=2.5;drive-=2}if(hd<-10){drive+=2}if(wd>16)drive-=1.5;if(wd<-16)drive+=1.5;let action='drive',best=Math.max(drive,shoot,mid);if(best===shoot)action='three';else if(best===mid)action='mid';if(r()<.18*ap.variance)action=pick(r,['drive','three','mid']);
 let attack,defense,points=1,txt;if(action==='three'){attack=atk.a.three*.72+atk.a.handle*.18+atk.a.clutch*.1;defense=def.a.perimeter;points=2;txt='外线三分'}else if(action==='mid'){attack=atk.a.mid*.76+atk.a.handle*.16+atk.a.clutch*.08;defense=def.a.perimeter*.78+def.a.speed*.22;txt='中距离单打'}else{attack=atk.a.finish*.38+atk.a.dunk*.25+atk.a.speed*.19+atk.a.strength*.18;defense=def.a.interior*.43+def.a.perimeter*.16+def.a.strength*.25+def.a.speed*.16;txt=atk.a.dunk>93&&r()<.38?'起飞扣篮':'强突篮下'}
 const close=(Math.max(sa,sb)>=8&&Math.abs(sa-sb)<=2);if(close)attack+=(atk.a.clutch-85)*.12+(ap.clutch||0);let p=clamp(.45+(attack-defense)*.011+rr(r,-.055,.055)*ap.variance,.18,.78);let made=r()<p;
 if((atk.id==='griffin'||def.id==='griffin')&&!posterDone&&r()<.34){posterDone=true;if(atk.id==='griffin'){log.push(`<span class="special">剧情：格里芬突然抓住一步空隙，直接起飞完成一次夸张隔扣。全场瞬间炸开——这一球只算正常得分，不额外改变胜负规则。</span>`)}else{log.push(`<span class="special">剧情：格里芬在协防位置追着你起跳，几乎把一次普通突破变成了隔扣名场面的反面教材。剧情不额外修改比分。</span>`)}}
 if(made){if(poss===0)sa+=points;else sb+=points;log.push(`<span class="made">${atk.name} ${txt}命中，${sa}:${sb}</span>`)}else{log.push(`<span class="miss">${atk.name} ${txt}没进。</span>`);const orb=clamp(.18+(atk.a.rebound-def.a.rebound)*.004,.07,.38);if(r()<orb){log.push(`<span class="special">${atk.name}抢到进攻篮板，继续持球。</span>`);poss=poss;continue}}
 poss=1-poss;
 }
 let winner=sa>sb?pa:pb;if(sa===sb){winner=r()<gameWinProb(a,b)?pa:pb;if(winner.id===pa.id)sa++;else sb++}return{winner,score:[sa,sb],log:important?log.slice(-26):[],notes:[...matchupNotes(a,b),...matchupNotes(b,a)].slice(0,4)};
}
function simulateRoundAll(ri,focusOppId){
 const t=career.tournament,ms=t.rounds[ri];ms.forEach((m,i)=>{if(m.winner)return;const important=m.a.id===player.id||m.b.id===player.id||(friendPlayer&&(m.a.id===friendPlayer.id||m.b.id===friendPlayer.id));const g=simulateGame(m.a,m.b,`${career.seed}|${career.age}|r${ri}|m${i}`,important);m.winner=g.winner;m.score=g.score;m.log=g.log;m.notes=g.notes});
 if(ri<3){const winners=ms.map(m=>m.winner);t.rounds[ri+1]=[];for(let i=0;i<winners.length;i+=2)t.rounds[ri+1].push({a:winners[i],b:winners[i+1],winner:null,score:null})}
 if(ri===2){const losers=ms.map(m=>m.winner.id===m.a.id?m.b:m.a);t.bronze={a:losers[0],b:losers[1],winner:null,score:null};}
 if(ri===3){t.champ=ms[0].winner;t.runner=ms[0].winner.id===ms[0].a.id?ms[0].b:ms[0].a;if(!t.bronze.winner){const bg=simulateGame(t.bronze.a,t.bronze.b,`${career.seed}|${career.age}|bronze`,false);t.bronze.winner=bg.winner;t.bronze.score=bg.score;}t.third=t.bronze.winner;awardTournamentPoints();}
}
function awardTournamentPoints(){const t=career.tournament;[[t.champ,10],[t.runner,6],[t.third,3]].forEach(([p,pts])=>{if(p)career.points[p.id]=(career.points[p.id]||0)+pts});if(t.champ?.id===player.id)career.crowns++;if(t.runner?.id===player.id)career.silvers++;if(t.third?.id===player.id)career.bronzes++;if(career.mode==='multi')updateRelationship(t);}
function updateRelationship(t){let met=false;for(const rd of t.rounds)for(const m of rd||[])if((m.a.id===player.id&&m.b.id===friendPlayer.id)||(m.b.id===player.id&&m.a.id===friendPlayer.id)){met=true;career.relationship.meetings++;const pp=PERSONALITIES[player.personality],fp=PERSONALITIES[friendPlayer.personality];career.relationship.score+=(pp.friend+fp.friend)/3-(pp.rival+fp.rival)/4}if(met){const s=career.relationship.score;career.relationship.label=s>3?'球场好友':s<-3?'宿敌':career.relationship.meetings>=3?'亦敌亦友':'竞争对手'}}
