function showMatchResult(m,opp){
 $('storyCard').classList.add('hidden');$('resultCard').classList.remove('hidden');const win=m.winner.id===player.id,r=RNG(`${career.seed}|post|${career.age}|${opp.id}`),op=PERSONALITIES[opp.personality||opp.p]||PERSONALITIES.duncan;let post;if(win){if(op.rival>=4&&r()<.72)post='“这场算你的。但你最好别以为以后都这样。”';else if(op.friend>=2&&r()<.7)post='“你今天打得更好。我认。下次继续。”';else post='“比分是你的，但我还没决定服不服。”'}else{if(op.rival>=4&&r()<.72)post='“就这样？我还以为你会让我更认真一点。”';else if(op.friend>=2)post='“比分结束了。明年再来，这场值得。”';else post='“今天我赢。至于下一次，等签表再说。”'};if(opp.id==='draymond'&&!win)post='“看吧，你来之前我就已经在这里赢过、吵过、再赢过了。”';if(friendPlayer&&opp.id===friendPlayer.id)post=win?'你们碰拳，但谁都没有说“下次让你”。':'朋友把球递回来：“这场我拿走，下次继续。”';
 $('matchResult').innerHTML=`<div class="result-title ${win?'win':'lose'}">${win?'晋级':'失利'}</div><div class="scoreline"><div class="name">${m.a.name}</div><div class="score">${m.score[0]} : ${m.score[1]}</div><div class="name">${m.b.name}</div></div><div class="matchup-notes">${(m.notes||[]).map(n=>`<div class="note">${n}</div>`).join('')}</div><div class="dialogue">${post}</div><div class="play-log">${(m.log||[]).map(x=>`<div class="play">${x}</div>`).join('')}</div>`;
 $('continueBtn').onclick=()=>afterFocusResult(m,win);
}
function afterFocusResult(m,win){const t=career.tournament,ri=t.roundIndex;if(ri===3){endSeason();return}if(win){t.roundIndex++;renderBracket();prepareFocusMatch()}else{if(ri===2){playBronzeForUser();return}completeTournamentAfterElimination()}}
function playBronzeForUser(){const t=career.tournament,other=t.bronze.a.id===player.id?t.bronze.b:t.bronze.a;$('resultCard').classList.add('hidden');$('storyCard').classList.remove('hidden');$('storyHeading').textContent=`季军赛 · ${other.name}`;$('storyBody').innerHTML=`<p>半决赛失利后，你还有最后一场。第三名不会让失败消失，但它决定你这一年最终站在哪一层。</p>${preStory(player,other)}`;$('playRoundBtn').textContent='争夺季军';$('playRoundBtn').onclick=()=>{const g=simulateGame(t.bronze.a,t.bronze.b,`${career.seed}|${career.age}|bronze`,true);t.bronze.winner=g.winner;t.bronze.score=g.score;t.third=g.winner;const m={...t.bronze,log:g.log,notes:g.notes};career.matchLog.push({age:career.age,round:'bronze',opp:other.name,oppId:other.id,win:m.winner.id===player.id,score:m.score});renderBracket();showBronzeResult(m,other)}}
function showBronzeResult(m,opp){$('storyCard').classList.add('hidden');$('resultCard').classList.remove('hidden');const win=m.winner.id===player.id;$('matchResult').innerHTML=`<div class="result-title ${win?'win':'lose'}">${win?'拿下季军':'第四名'}</div><div class="scoreline"><div class="name">${m.a.name}</div><div class="score">${m.score[0]} : ${m.score[1]}</div><div class="name">${m.b.name}</div></div><div class="play-log">${m.log.map(x=>`<div class="play">${x}</div>`).join('')}</div>`;$('continueBtn').onclick=()=>{completeTournamentAfterElimination(true)}}
function completeTournamentAfterElimination(bronzeDone=false){
 const t=career.tournament,start=bronzeDone?3:t.roundIndex+1;for(let ri=start;ri<4;ri++)simulateRoundAll(ri);renderBracket();endSeason();
}
function placementFor(id){const t=career.tournament;if(t.champ?.id===id)return 1;if(t.runner?.id===id)return 2;if(t.third?.id===id)return 3;for(let ri=0;ri<t.rounds.length;ri++){const m=(t.rounds[ri]||[]).find(x=>x.a.id===id||x.b.id===id);if(m&&m.winner&&m.winner.id!==id)return ri===2?4:ri===1?'8强':'16强'}return'16强'}
function placement(){return placementFor(player.id)}
function endSeason(){
 const t=career.tournament;if(!t.champ){for(let ri=t.roundIndex;ri<4;ri++)simulateRoundAll(ri)}const pl=placement();career.history.push({age:career.age,place:pl,friendPlace:career.mode==='multi'?placementFor(friendPlayer.id):null,champ:t.champ?.name,runner:t.runner?.name,third:t.third?.name,injury:career.currentInjury?.type||null,condition:Math.round(conditionFor(player))});renderBracket();renderHistory();$('storyCard').classList.add('hidden');$('resultCard').classList.remove('hidden');let medal=pl===1?'🏆 冠军':pl===2?'🥈 亚军':pl===3?'🥉 季军':`${pl}`;$('matchResult').innerHTML=`<div class="result-title ${pl===1?'win':''}">${career.age}岁 · ${medal}</div><p class="story-body">本届冠军：<b>${t.champ.name}</b>；亚军：${t.runner.name}；季军：${t.third.name}。</p>${career.currentInjury?`<div class="note injury">本赛季受到${career.currentInjury.type}影响，身体状态降至 ${Math.round(conditionFor(player))}。</div>`:''}`;$('continueBtn').textContent=career.age>=career.retirement?'结束生涯':'进入下一岁';$('continueBtn').onclick=()=>{career.age++;newSeason()};
}
function renderHistory(){if(!career)return;const rows=career.history.slice().reverse().map(h=>{const c=h.place===1?'gold':h.place===2?'silver':h.place===3?'bronze':'';return `<div class="career-row"><b>${h.age}岁</b><span>${h.injury?`<span class="injury">${h.injury}</span> · `:''}冠军 ${h.champ||'-'}${career.mode==='multi'?` · ${friendPlayer.name}: ${typeof h.friendPlace==='number'?(h.friendPlace===1?'冠军':h.friendPlace===2?'亚军':h.friendPlace===3?'季军':'第四'):h.friendPlace}`:''}</span><span class="medal ${c}">${typeof h.place==='number'?(h.place===1?'冠军':h.place===2?'亚军':h.place===3?'季军':'第四'):h.place}</span></div>`}).join('');$('careerHistory').innerHTML=rows||'<div class="muted">18岁的第一届还没结束。</div>'}
function finishCareer(){career.alive=false;show('retire');const ranking=buildRanking();$('legacySummary').innerHTML=`<span class="eyebrow">CAREER TOTAL</span><h3>#${player.number} ${player.name}</h3><div class="summary-grid"><div class="summary-stat">冠军<b>${career.crowns}</b></div><div class="summary-stat">亚军<b>${career.silvers}</b></div><div class="summary-stat">季军<b>${career.bronzes}</b></div><div class="summary-stat">退役年龄<b>${career.retirement}</b></div></div>${career.mode==='multi'?`<p class="muted">你与 ${friendPlayer.name}：${career.relationship.label} · 正面相遇 ${career.relationship.meetings} 次。</p>`:''}`;$('leaderboard').innerHTML=ranking.map((x,i)=>`<div class="leader-row ${x.id===player.id?'me':''} ${friendPlayer&&x.id===friendPlayer.id?'friendrow':''}"><span class="leader-rank">${i+1}</span><span><b>${x.name}</b><br><small class="muted">${x.pos||player.pos}</small></span><span>${x.medals}</span><span class="leader-score">${x.score.toFixed(1)}</span></div>`).join('');$('careerNarrative').innerHTML=makeNarrative(ranking)}
function buildRanking(){const everyone=[...NBA_POOL,player,...(career.mode==='multi'?[friendPlayer]:[])];return everyone.map(p=>{const pts=career.points[p.id]||0;const strength=(streetOVR(p)-82)*.22;const noise=(hash32(career.seed+pKey(p))%1000)/1000*2.5;return{id:p.id,name:p.name,pos:p.pos,score:pts+strength+noise,medals:pts>=20?'多次领奖':pts>=10?'冠军级':pts>=3?'上过领奖台':'—'}}).sort((a,b)=>b.score-a.score)}
function makeNarrative(rank){const myRank=rank.findIndex(x=>x.id===player.id)+1;const best=career.history.filter(h=>typeof h.place==='number').sort((a,b)=>a.place-b.place)[0];const injuries=career.injuries.length;const iconic=['jordan','kobe','lebron','curry','shaq','durant','iverson','griffin','edwards'];const notable=career.matchLog.filter(m=>m.win&&iconic.includes(m.oppId)).map(m=>m.opp).filter((x,i,a)=>a.indexOf(x)===i).slice(0,5);let tone=career.crowns>=4?'你最终成为了这条街反复出现的名字。别人谈起一届赛事时，常常先问你有没有参赛。':career.crowns>=1?'你没有统治每一年，但真正站上过最高处。那让后来的每个对手都不能把你当普通签位。':'你从未把冠军变成自己的东西，但这并不等于生涯没有重量：你一次次回到签表里，让不同类型的历史强者都必须认真准备。';let rel=career.mode==='multi'?`你和 ${friendPlayer.name} 的关系最后被这条街定义成“${career.relationship.label}”。你们真正正面对上 ${career.relationship.meetings} 次，有些年份甚至直到签表出来才知道会不会相遇。`:'';return `<p>${player.name}从18岁开始参加路人王，最终在${career.retirement}岁退役。${tone}</p><p>你的最终街头历史排名是第 <b>${myRank}</b>。生涯拿到${career.crowns}冠、${career.silvers}次亚军、${career.bronzes}次季军；经历${injuries}次被记录的伤病事件。${best?`最好成绩出现在${best.age}岁。`:''}</p><p>${rel}</p>${notable.length?`<p>你生涯里真正留下分量的胜场包括击败 ${notable.join('、')}。这些名字让你的履历不只剩奖牌数量。</p>`:''}<p>最重要的是，这条履历不是由一个固定模板决定：你的外线、身体、对位和性格让某些签位变成优势，也让另一些对手天然难打。下一次重开，即使仍用同一套能力模板，抽签、伤病、手感和关键球也会把生涯推向另一条线。</p>`}
$('careerMenuBtn').onclick=()=>show('menu');$('retireMenuBtn').onclick=()=>show('menu');$('restartBtn').onclick=()=>show('menu');

// restore local player
try{const saved=JSON.parse(localStorage.getItem('sk2_player')||'null');if(saved){player=saved}}catch(e){}
renderMulti();
