function careerSeed(){return `${Date.now()}-${Math.random()}-${player.name}`}
function startCareer(mode,sharedSeed=''){
 const seed=mode==='multi'?`MULTI|${sharedSeed}|${[pKey(player),pKey(friendPlayer)].sort().join('|')}`:careerSeed(),r=RNG(seed),pers=PERSONALITIES[player.personality];const careerPlayers=mode==='multi'?[player,friendPlayer]:[player];const physical=careerPlayers.reduce((s,p)=>s+(p.a.strength+p.a.speed)/2,0)/careerPlayers.length;const durabilityBonus=careerPlayers.reduce((s,p)=>s+(PERSONALITIES[p.personality].injury<.95?1:0),0)/careerPlayers.length;let retirement=Math.round(34+(physical-80)/10+rr(r,-1.5,2.5)+durabilityBonus);retirement=clamp(retirement,32,40);
 career={mode,seed,sharedSeed,age:18,retirement,season:0,crowns:0,silvers:0,bronzes:0,history:[],points:{},injuries:[],conditions:{},currentInjuries:{},matchLog:[],relationship:{score:0,meetings:0,label:'陌生人'},tournament:null,alive:true};NBA_POOL.forEach(x=>career.points[x.id]=0);career.points[player.id]=0;career.conditions[pKey(player)]=100;if(mode==='multi'){career.points[friendPlayer.id]=0;career.conditions[pKey(friendPlayer)]=100;}
 show('career');newSeason();
}
function ageCurve(p,age){if(p.type!=='custom')return 1;let peak=age<=22?.94+(age-18)*.015:age<=29?1:age<=33?1-(age-29)*.018:1-(age-33)*.035;return clamp(peak,.78,1)}
function effective(p,age,condition=100){let f=ageCurve(p,age)*(0.82+condition/555);let a={};Object.keys(p.a).forEach(k=>a[k]=clamp(p.a[k]*f,55,99));if(p.type==='custom'){const hd=(p.h-198)/5,wd=(p.w-96)/10;a.interior=clamp(a.interior+hd*1.6+wd*.7,50,99);a.rebound=clamp(a.rebound+hd*1.5+wd*.6,50,99);a.strength=clamp(a.strength+wd*2.0+hd*.5,50,99);a.speed=clamp(a.speed-hd*1.0-wd*1.0,50,99);a.handle=clamp(a.handle-hd*.7-wd*.45,50,99);a.dunk=clamp(a.dunk+hd*.45,50,99)}return{...p,a}}
function injuryEventFor(p){
 const key=pKey(p),r=RNG(`${career.seed}|inj|${career.age}|${key}`),pers=PERSONALITIES[p.personality];let condition=conditionFor(p);let base=.035+Math.max(0,career.age-27)*.013;const explosive=(p.a.dunk+p.a.speed)/2;const durability=(p.a.strength+p.a.rebound)/2;base*=pers.injury;base*=1+(explosive-durability)/180;
 if(r()<base){const severe=r()<.14&&career.age>29;const moderate=!severe&&r()<.45;const loss=severe?rr(r,18,28):moderate?rr(r,9,16):rr(r,4,9);condition=clamp(100-loss,62,100);const type=pick(r,severe?['膝部伤势','跟腱拉伤','背部伤势']:moderate?['脚踝扭伤','膝盖酸痛','腿筋拉伤']:['手指挫伤','轻微脚踝不适','背部紧张']);career.conditions[key]=condition;const evt={type,severe,loss:Math.round(loss),player:p.name};career.injuries.push({age:career.age,...evt});return evt}
 condition=clamp(condition+rr(r,3,9),75,100);career.conditions[key]=condition;return null;
}
function newSeason(){
 career.season++;if(career.age>career.retirement){finishCareer();return}career.currentInjuries={};career.currentInjuries[pKey(player)]=injuryEventFor(player);if(career.mode==='multi')career.currentInjuries[pKey(friendPlayer)]=injuryEventFor(friendPlayer);career.currentInjury=career.currentInjuries[pKey(player)];career.tournament=makeTournament();renderCareerHeader();renderBracket();prepareFocusMatch();
}
function entrantCopy(x){return JSON.parse(JSON.stringify(x))}
function makeTournament(){
 const r=RNG(`${career.seed}|draw|${career.age}`),pool=NBA_POOL.map(entrantCopy),entrants=[player];if(career.mode==='multi')entrants.push(friendPlayer);entrants.sort((a,b)=>pKey(a).localeCompare(pKey(b)));while(entrants.length<16){const i=Math.floor(r()*pool.length);const x=pool.splice(i,1)[0];if(!entrants.find(e=>e.id===x.id))entrants.push(x)}for(let i=entrants.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[entrants[i],entrants[j]]=[entrants[j],entrants[i]]}
 const rounds=[[]];for(let i=0;i<16;i+=2)rounds[0].push({a:entrants[i],b:entrants[i+1],winner:null,score:null});return{entrants,rounds,roundIndex:0,bronze:null,champ:null,runner:null,third:null,focusDone:false};
}
function participantClass(p){if(p.id===player.id)return'focus';if(friendPlayer&&p.id===friendPlayer.id)return'friend';return''}
function renderCareerHeader(){
 $('careerModeLabel').textContent=career.mode==='multi'?'FRIEND CAREER':'SOLO CAREER';$('careerTitle').textContent=`${career.age}岁 · 第${career.season}届路人王`;$('crownCount').textContent=career.crowns;$('retireAgeLabel').textContent=`预计退役 ${career.retirement} 岁`;
 const myCondition=conditionFor(player),ovr=streetOVR(effective(player,career.age,myCondition));$('seasonStatus').innerHTML=`<div class="status-box"><span>年龄</span><b>${career.age}</b></div><div class="status-box"><span>当届街球值</span><b>${ovr}</b></div><div class="status-box ${myCondition<85?'warn':''}"><span>身体状态</span><b>${Math.round(myCondition)}</b></div><div class="status-box"><span>冠军</span><b>${career.crowns}</b></div>`;renderHistory();
}
function renderBracket(){
 const t=career.tournament,names=['16强','8强','半决赛','决赛'];$('tournamentStage').textContent=names[Math.min(t.roundIndex,3)];let html='';for(let ri=0;ri<4;ri++){const ms=t.rounds[ri]||[];html+=`<div class="round-col"><h4>${names[ri]}</h4>`;if(!ms.length){const count=8/(2**ri);for(let i=0;i<count;i++)html+='<div class="match"><div class="slot"><span>待定</span></div><div class="slot"><span>待定</span></div></div>'}else ms.forEach(m=>{html+=`<div class="match"><div class="slot ${m.winner&&m.winner.id===m.a.id?'winner':''} ${participantClass(m.a)}"><span>${m.a.name}</span>${m.score?`<b>${m.score[0]}</b>`:''}</div><div class="slot ${m.winner&&m.winner.id===m.b.id?'winner':''} ${participantClass(m.b)}"><span>${m.b.name}</span>${m.score?`<b>${m.score[1]}</b>`:''}</div></div>`});html+='</div>'}$('bracket').innerHTML=html;
 $('bronzeBox').innerHTML=t.bronze?`<div class="bronze-match"><b>季军赛</b>　${t.bronze.a.name} ${t.bronze.score?t.bronze.score[0]:'-'} : ${t.bronze.score?t.bronze.score[1]:'-'} ${t.bronze.b.name}${t.third?`　<span class="bronze">季军：${t.third.name}</span>`:''}</div>`:'';
}
function findFocusMatch(){const ms=career.tournament.rounds[career.tournament.roundIndex]||[];return ms.find(m=>m.a.id===player.id||m.b.id===player.id)||null}
function prepareFocusMatch(){
 $('resultCard').classList.add('hidden');$('storyCard').classList.remove('hidden');const m=findFocusMatch();if(!m){completeTournamentAfterElimination();return}const opp=m.a.id===player.id?m.b:m.a;const story=preStory(player,opp);$('storyHeading').textContent=`${['16强','8强','半决赛','决赛'][career.tournament.roundIndex]} · ${opp.name}`;$('storyBody').innerHTML=story;$('playRoundBtn').textContent='开始比赛';$('playRoundBtn').onclick=playFocusRound;
}
function personalityLine(p,r){const per=PERSONALITIES[p.personality||p.p]||PERSONALITIES.duncan;return pick(r,per.lines)}
function preStory(me,opp){const r=RNG(`${career.seed}|storypre|${career.age}|${opp.id}`),mp=PERSONALITIES[me.personality],op=PERSONALITIES[opp.personality||opp.p]||PERSONALITIES.duncan;let context='';const mismatch=POS_NUM[opp.pos]-POS_NUM[me.pos];if(mismatch>=2)context=`你面对的是明显更大的${opp.pos}。你的速度会有空间，但一旦被他把位置压进油漆区，对抗会很难受。`;else if(mismatch<=-2)context=`你拥有明显尺寸优势，但如果脚步跟不上，外线会被连续拉开。`;else context='这是尺寸接近的对位，比赛更可能由招牌技能和临场手感决定。';let lore=PLAYER_LORE[opp.id]?`<div class="story-note">${PLAYER_LORE[opp.id]}</div>`:'';let special=opp.id==='griffin'?'<div class="story-note">场边已经有人举起手机——格里芬今天显然想找一次能把全场点燃的隔扣。</div>':'';let rel='';if(friendPlayer&&opp.id===friendPlayer.id)rel=`<div class="dialogue friendline">你们终于在正式签表里撞上。现在的关系：${career.relationship.label}。</div>`;let buildNote='';if(me.a.three-(opp.a?.perimeter||82)>8)buildNote=`你的${me.templates?.three||'三分'}投射模板在这个对位里很有价值，拉开空间可能是最直接的解法。`;else if(me.a.strength-(opp.a?.strength||82)>10)buildNote=`你的力量模板明显占优，系统会提高背身和强突的选择频率。`;else if(me.a.speed-(opp.a?.speed||82)>10)buildNote=`你的速度是这一场最明显的突破口，第一步会得到额外收益。`;return `<p>${career.age}岁的你走进球场，${opp.name}已经在另一侧等着。</p><div class="dialogue">“${personalityLine(opp,r)}”</div><div class="dialogue friendline">你回了一句：“${personalityLine(me,RNG(`${career.seed}|selftalk|${career.age}|${opp.id}`))}”</div>${lore}<p>${context}</p>${buildNote?`<div class="story-note">${buildNote}</div>`:''}${rel}${special}<div class="story-note">你的性格：${mp.name}。这会影响你在关键球的波动与赛后关系。</div>`}
function playFocusRound(){
 const t=career.tournament,m=findFocusMatch(),opp=m.a.id===player.id?m.b:m.a;simulateRoundAll(t.roundIndex,opp.id);renderBracket();const fm=(t.rounds[t.roundIndex]||[]).find(x=>(x.a.id===player.id||x.b.id===player.id));const result=fm;career.matchLog.push({age:career.age,round:t.roundIndex,opp:opp.name,oppId:opp.id,win:result.winner.id===player.id,score:result.score});showMatchResult(result,opp);t.focusDone=true;
}
