'use strict';
const $=id=>document.getElementById(id); const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
let player=null,friend=null,lastBattle=null;
let career={age:18,round:0,crowns:0,history:[],active:true};
function hash32(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rngFrom(seed){let x=hash32(seed)||123456789;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return((x>>>0)/4294967296)}}
function enc(obj){const s=unescape(encodeURIComponent(JSON.stringify(obj)));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function dec(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return JSON.parse(decodeURIComponent(escape(atob(s))))}
function playerCode(p){return'LRW1.'+enc({v:1,n:p.name,p:p.pos,h:p.height,w:p.weight,a:p.a,t:p.templates})}
function parsePlayerCode(code){if(!code.startsWith('LRW1.'))throw Error('不是有效的 LRW1 角色码');const d=dec(code.slice(5));if(!d.n||!d.p||!d.a)throw Error('角色码内容不完整');return{name:d.n,pos:d.p,height:d.h,weight:d.w,a:d.a,templates:d.t||{},code:code.trim()}}
function overall(a){return Math.round((a.finish+a.mid+a.three+a.handle+a.pass+a.defense+a.strength+a.speed+a.clutch)/9)}
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),1600)}
function copyText(t){if(navigator.clipboard&&location.protocol==='https:')navigator.clipboard.writeText(t).then(()=>toast('已复制')).catch(()=>fallbackCopy(t));else fallbackCopy(t)}
function fallbackCopy(t){const ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('已复制')}
function skillCost(){let sum=0;Object.keys(SKILLS).forEach(k=>{sum+=SKILLS[k].pool[+$('skill-'+k).value][2]});return sum}
function renderBuilder(){const box=$('skillBuilder');box.innerHTML='';Object.entries(SKILLS).forEach(([k,v])=>{const row=document.createElement('div');row.className='skillrow';const sel=document.createElement('select');sel.id='skill-'+k;v.pool.forEach((p,i)=>{const op=document.createElement('option');op.value=i;op.textContent=`${p[0]} · ${p[1]} (${p[2]}点)`;sel.appendChild(op)});sel.value=DEFAULT_IDX[k];sel.onchange=updateBudget;row.innerHTML=`<div class="skillname">${v.label}</div>`;row.appendChild(sel);const r=document.createElement('div');r.className='rating';r.id='rating-'+k;row.appendChild(r);box.appendChild(row)});updateBudget()}
function updateBudget(){let sum=0;Object.keys(SKILLS).forEach(k=>{const idx=+$('skill-'+k).value;const p=SKILLS[k].pool[idx];sum+=p[2];$('rating-'+k).textContent=p[1]});$('budgetUsed').textContent=`${sum} / ${MAX_BUDGET}`;$('budgetUsed').className=sum<=MAX_BUDGET?'ok':'bad';$('createPlayerBtn').disabled=sum>MAX_BUDGET;$('createPlayerBtn').style.opacity=sum>MAX_BUDGET?.45:1}
function buildPlayer(){const cost=skillCost();if(cost>MAX_BUDGET){toast('天赋点超预算');return}const a={},templates={};Object.keys(SKILLS).forEach(k=>{const p=SKILLS[k].pool[+$('skill-'+k).value];a[k]=p[1];templates[k]=p[0]});player={name:$('pName').value.trim()||'匿名球员',pos:$('pPos').value,height:+$('pHeight').value,weight:+$('pWeight').value,a,templates};player.code=playerCode(player);career={age:18,round:0,crowns:0,history:[],active:true};friend=null;save();renderAll();$('builder').classList.add('hidden');$('playerCardSection').classList.remove('hidden');toast('角色已创建')}
function renderPlayerCard(p,target='playerCard'){const a=p.a;$(target).innerHTML=`<div class="playercard"><div class="pc-top"><div><div class="pc-name">${escapeHtml(p.name)}</div><div class="meta">${p.pos} · ${p.height||'—'}cm · ${p.weight||'—'}kg</div></div><div class="ovr">${overall(a)}</div></div><div class="attrgrid">${Object.entries(SKILLS).map(([k,v])=>`<div class="attr">${v.label}<b>${a[k]}</b></div>`).join('')}</div><div class="code">${p.code||playerCode(p)}</div></div>`}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function save(){localStorage.setItem('lrw-player-v1',player?JSON.stringify(player):'');localStorage.setItem('lrw-career-v1',JSON.stringify(career))}
function load(){try{const p=localStorage.getItem('lrw-player-v1');if(p)player=JSON.parse(p);const c=localStorage.getItem('lrw-career-v1');if(c)career=JSON.parse(c)}catch(e){}}
function switchTab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));['build','career','battle'].forEach(t=>$('tab-'+t).classList.toggle('hidden',t!==name));if(name==='career')renderCareer();if(name==='battle')renderBattle()}
function renderAll(){if(player){player.code=player.code||playerCode(player);renderPlayerCard(player);$('careerEmpty').classList.add('hidden');$('careerGame').classList.remove('hidden');$('battleNoPlayer').classList.add('hidden');$('battleArea').classList.remove('hidden')}else{$('playerCardSection').classList.add('hidden');$('builder').classList.remove('hidden');$('careerEmpty').classList.remove('hidden');$('careerGame').classList.add('hidden');$('battleNoPlayer').classList.remove('hidden');$('battleArea').classList.add('hidden')}renderCareer();renderBattle()}
function roadFor(){const band=clamp(Math.floor((career.age-18)/4),0,3);return ROAD[player.pos][band]}
function renderCareer(){if(!player)return;$('careerAge').textContent=career.age;$('careerCrowns').textContent=career.crowns;$('careerSeasonText').textContent=`第 ${career.age-17} 届路人王 · ${player.pos} 路线`;$('careerMini').innerHTML=`<div class="sub">${escapeHtml(player.name)} · OVR ${overall(player.a)} · 当前第 ${Math.min(career.round+1,4)} 关</div>`;const road=roadFor();$('ladder').innerHTML=road.map((n,i)=>`<div class="round ${i<career.round?'done':i===career.round?'current':''}"><div class="num">${i+1}</div><div><div class="opp">${n}</div><div class="tiny">${i===3?'本届 Boss':'晋级战'}</div></div><div class="tag">${i<career.round?'已过':i===career.round?'当前':'未解锁'}</div></div>`).join('');renderCareerStory();renderHistory()}
function renderCareerStory(){if(career.age>35){$('storyTitle').textContent='生涯落幕';$('storyText').innerHTML=`<p>从18岁到35岁，你一共拿下 <b class="champ">${career.crowns} 次路人王冠军</b>。</p><p>${career.crowns>=10?'你的名字已经成了街头时代的代名词。':career.crowns>=5?'你留下了一段足够被反复讲述的街头生涯。':'你没能统治整个时代，但每一次上场都留下了记录。'}</p>`;$('fightCareerBtn').classList.add('hidden');return}$('fightCareerBtn').classList.remove('hidden');const opp=OPP[roadFor()[career.round]];$('storyTitle').textContent=`第 ${career.round+1} 关 · ${opp.name}`;$('storyText').innerHTML=`<p>${career.age===18&&career.round===0?'你第一次走进路人王主场。围栏外的人还不知道你的名字。':''}</p><p>${opp.intro}</p><div class="quote">${career.round===3?'赢下这一场，你就是 '+career.age+' 岁路人王。':'这一关没有退路，输球就结束这一岁的征程。'}</div>`}
function renderHistory(){if(!career.history.length){$('careerHistory').innerHTML='<div class="sub">还没有参加过完整的一届。</div>';return}$('careerHistory').innerHTML=career.history.slice().reverse().map(h=>`<div class="hist"><span>${h.age}岁 · ${h.bestRound}</span><span class="${h.champion?'champ':''}">${h.champion?'🏆 冠军':'止步'}</span></div>`).join('')}
function endYear(champion,bestRound){career.history.push({age:career.age,champion,bestRound});if(champion)career.crowns++;career.age++;career.round=0;save();renderCareer()}
function careerFight(){const opp=OPP[roadFor()[career.round]];const seed=`career|${player.code}|${career.age}|${career.round}`;const r=simulate1v1(player,opp,seed);showCareerResult(r,opp)}
function showCareerResult(r,opp){$('careerResultCard').classList.remove('hidden');$('storyCard').classList.add('hidden');$('ladderCard').classList.add('hidden');$('careerResult').innerHTML=renderMatch(r,player,opp)+`<div class="quote">${r.winner==='A'?opp.win:opp.lose}</div>`;$('careerContinueBtn').textContent=r.winner==='A'?(career.round===3?'领取本届冠军':'进入下一关'):'结束这一岁';$('careerContinueBtn').onclick=()=>{if(r.winner==='A'){if(career.round===3)endYear(true,'冠军');else{career.round++;save();$('careerResultCard').classList.add('hidden');$('storyCard').classList.remove('hidden');$('ladderCard').classList.remove('hidden');renderCareer()}}else{endYear(false,`第${career.round+1}关`);$('careerResultCard').classList.add('hidden');$('storyCard').classList.remove('hidden');$('ladderCard').classList.remove('hidden')} };window.scrollTo({top:0,behavior:'smooth'})}
function shotChoice(a,rng){const weights=[['三分','three',Math.max(8,a.three-75)],['中投','mid',Math.max(8,a.mid-75)],['突破','finish',Math.max(8,(a.finish+a.speed+a.strength)/3-75)]];let total=weights.reduce((s,x)=>s+x[2],0),x=rng()*total;for(const w of weights){x-=w[2];if(x<=0)return w}return weights[2]}
function possession(att,def,rng,late){const a=att.a,d=def.a;const tov=clamp(.08+(d.defense-a.handle)*.0035,.035,.19);if(rng()<tov)return{pts:0,text:`${att.name} 试图变向创造空间，但被 ${def.name} 逼出失误。`,cls:'turnover'};const [label,key]=shotChoice(a,rng);let p;if(key==='three')p=.30+(a.three-80)*.0065+(a.handle-85)*.0015-(d.defense-85)*.0035;else if(key==='mid')p=.38+(a.mid-80)*.006+(a.handle-85)*.001-(d.defense-85)*.003;else p=.43+(a.finish-80)*.005+(a.speed-85)*.002+(a.strength-d.strength)*.0018-(d.defense-85)*.0022;if(late)p+=(a.clutch-85)*.0025;p=clamp(p,.20,.78);const make=rng()<p;const pts=make?(key==='three'?2:1):0;const moves={three:['撤步三分','超远干拔','横移后三分'],mid:['急停中投','后仰中距离','试探步跳投'],finish:['强突上篮','变向杀入篮下','顶着对抗终结']};const mv=moves[key][Math.floor(rng()*moves[key].length)];return{pts,text:`${att.name} ${mv}——${make?'命中':'偏出'}。`,cls:make?'made':'miss'}}
function normalizeOpp(o){if(o.code)return o;return{name:o.name,pos:o.pos,height:198,weight:95,a:o.a,code:'CPU-'+o.name}}
function simulate1v1(pa,pb,seed){const A=normalizeOpp(pa),B=normalizeOpp(pb),rng=rngFrom(seed);let sa=0,sb=0,poss=rng()<.5?'A':'B',log=[],n=0;while(n<80){const late=Math.max(sa,sb)>=8;const res=poss==='A'?possession(A,B,rng,late):possession(B,A,rng,late);if(poss==='A')sa+=res.pts;else sb+=res.pts;log.push({who:poss,text:res.text,cls:res.cls,score:`${sa}:${sb}`});n++;if((sa>=11||sb>=11)&&Math.abs(sa-sb)>=2)break;if(sa>=15||sb>=15)break;poss=poss==='A'?'B':'A'}return{mode:'1v1',seed,scoreA:sa,scoreB:sb,winner:sa>sb?'A':'B',log}}
function renderMatch(r,A,B,teams=null){const aName=escapeHtml(A.name),bName=escapeHtml(B.name);let teamHtml='';if(teams)teamHtml=`<div class="teamline">${teams.A.map(x=>`<div class="ally"><b>${escapeHtml(x.name)}</b><small>${x.role} · ${x.ovr}</small></div>`).join('')}</div><div class="vs">VS</div><div class="teamline">${teams.B.map(x=>`<div class="ally"><b>${escapeHtml(x.name)}</b><small>${x.role} · ${x.ovr}</small></div>`).join('')}</div>`;return`<div class="section-title ${r.winner==='A'?'resultWin':'resultLose'}">${r.winner==='A'?aName:bName} 获胜</div><div class="vs"><span>${aName}</span><span class="score">${r.scoreA} : ${r.scoreB}</span><span>${bName}</span></div>${teamHtml}<div class="sub">Seed: ${escapeHtml(r.seed)}</div><div class="log" style="margin-top:10px">${r.log.map((x,i)=>`<div class="play ${x.cls}"><b>${i+1}. ${x.score}</b>　${escapeHtml(x.text)}</div>`).join('')}</div>`}
function roleForPos(pos){return pos==='PG'||pos==='SG'?'G':pos==='SF'?'W':'B'}
function allyFrom(entry,role){const base=entry[1],n=entry[0];return{name:n,role,ovr:base,a:{finish:base,mid:base,three:role==='B'?Math.max(76,base-12):base-2,handle:role==='B'?base-10:base-1,pass:base-2,defense:base-1,strength:role==='G'?base-10:base,speed:role==='B'?base-10:base-1,clutch:base}}}
function draftAllies(p,rng){const role=roleForPos(p.pos);const needed=role==='G'?['W','B']:role==='W'?['G','B']:['G','W'];return[{name:p.name,role:p.pos,ovr:overall(p.a),a:p.a},...needed.map(r=>allyFrom(ALLIES[r][Math.floor(rng()*ALLIES[r].length)],r))]}
function teamMetrics(team){const avg=k=>team.reduce((s,x)=>s+x.a[k],0)/3;const spacing=avg('three'),creation=(avg('handle')+avg('pass'))/2,inside=(avg('finish')+avg('strength'))/2,def=avg('defense'),cl=avg('clutch');return{spacing,creation,inside,def,cl,off:(spacing+creation+inside)/3}}
function simulate3v3(pa,pb,seed){const rng=rngFrom(seed),A=draftAllies(pa,rng),B=draftAllies(pb,rng),ma=teamMetrics(A),mb=teamMetrics(B);let sa=0,sb=0,poss=rng()<.5?'A':'B',log=[],n=0;while(n<100){const atk=poss==='A'?A:B,am=poss==='A'?ma:mb,dm=poss==='A'?mb:ma;const scorer=atk[Math.floor(rng()*3)];let isThree=rng()<clamp(.30+(am.spacing-85)*.008,.16,.55);let p=(isThree?.31:.46)+(am.off-85)*.004-(dm.def-85)*.003+(Math.max(sa,sb)>=17?(am.cl-88)*.002:0);p=clamp(p,.23,.72);const make=rng()<p,pts=make?(isThree?2:1):0;if(poss==='A')sa+=pts;else sb+=pts;log.push({who:poss,score:`${sa}:${sb}`,cls:make?'made':'miss',text:`${scorer.name} ${isThree?'外线出手':'切入终结'}——${make?'命中':'没进'}。`});n++;if((sa>=21||sb>=21)&&Math.abs(sa-sb)>=2)break;if(sa>=25||sb>=25)break;poss=poss==='A'?'B':'A'}return{mode:'3v3',seed,scoreA:sa,scoreB:sb,winner:sa>sb?'A':'B',log,teams:{A,B}}}
function renderBattle(){if(!player)return;renderCpuOpps();if(friend){$('friendPreview').classList.remove('hidden');$('friendPreview').innerHTML=`<div class="playercard"><div class="pc-top"><div><div class="pc-name">${escapeHtml(friend.name)}</div><div class="meta">${friend.pos} · OVR ${overall(friend.a)}</div></div><div class="ovr">${overall(friend.a)}</div></div></div>`}}
function renderCpuOpps(){const band=ROAD[player.pos][3];$('cpuOpponents').innerHTML=[...new Set(band)].map(n=>`<button class="btn ghost small cpuBtn" data-cpu="${n}">${n}<div class="tiny">OVR ${overall(OPP[n].a)}</div></button>`).join('');document.querySelectorAll('.cpuBtn').forEach(b=>b.onclick=()=>startCpu(b.dataset.cpu))}
function loadFriend(){try{friend=parsePlayerCode($('friendCode').value.trim());renderBattle();toast('朋友角色读取成功')}catch(e){toast(e.message)}}
function seedToken(){return Math.random().toString(36).slice(2,10)}
function createMatchCode(A,B,mode,seed){return'VS1.'+enc({v:1,a:A.code||playerCode(A),b:B.code||playerCode(B),m:mode,s:seed})}
function parseMatchCode(c){if(!c.startsWith('VS1.'))throw Error('不是有效 VS1 比赛码');return dec(c.slice(4))}
function startFriend(mode,seed=null){if(!friend){toast('先导入朋友角色码');return}seed=seed||seedToken();const r=mode==='3v3'?simulate3v3(player,friend,seed):simulate1v1(player,friend,seed);showBattle(r,player,friend,mode)}
function startCpu(name){const cpu=normalizeOpp(OPP[name]);cpu.code='CPU-'+name;const seed=seedToken();const r=simulate1v1(player,cpu,seed);showBattle(r,player,cpu,'1v1',true)}
function showBattle(r,A,B,mode,isCpu=false){lastBattle={r,A,B,mode,isCpu};$('battleResultCard').classList.remove('hidden');$('battleResult').innerHTML=renderMatch(r,A,B,r.teams);const code=isCpu?'CPU 对战不生成好友比赛码':createMatchCode(A,B,mode,r.seed);$('matchCodeBox').textContent=code;$('copyMatchCode').disabled=isCpu;$('copyMatchCode').style.opacity=isCpu?.45:1;$('copyMatchCode').onclick=()=>!isCpu&&copyText(code);$('rematchBtn').onclick=()=>{if(isCpu)startCpu(B.name);else startFriend(mode)};$('battleResultCard').scrollIntoView({behavior:'smooth',block:'start'})}
function replayMatch(){try{const d=parseMatchCode($('matchCodeInput').value.trim()),A=parsePlayerCode(d.a),B=parsePlayerCode(d.b);const r=d.m==='3v3'?simulate3v3(A,B,d.s):simulate1v1(A,B,d.s);lastBattle={r,A,B,mode:d.m,isCpu:false};$('battleResultCard').classList.remove('hidden');$('battleResult').innerHTML=renderMatch(r,A,B,r.teams);$('matchCodeBox').textContent=$('matchCodeInput').value.trim();$('copyMatchCode').disabled=false;$('copyMatchCode').style.opacity=1;$('copyMatchCode').onclick=()=>copyText($('matchCodeBox').textContent);$('rematchBtn').onclick=()=>toast('复现模式保持原种子；新比赛请从好友对战发起');$('battleResultCard').scrollIntoView({behavior:'smooth',block:'start'});toast('已按比赛码复现')}catch(e){toast(e.message)}}
function init(){renderBuilder();load();document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchTab(b.dataset.go));$('createPlayerBtn').onclick=buildPlayer;$('copyPlayerCode').onclick=()=>player&&copyText(player.code);$('editBuild').onclick=()=>{if(confirm('重新捏人会重置当前路人王生涯，继续吗？')){$('builder').classList.remove('hidden');$('playerCardSection').classList.add('hidden')}};$('fightCareerBtn').onclick=careerFight;$('loadFriendBtn').onclick=loadFriend;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>startFriend(b.dataset.mode));$('replayMatchBtn').onclick=replayMatch;if(player){$('builder').classList.add('hidden');$('playerCardSection').classList.remove('hidden')}renderAll()}
document.addEventListener('DOMContentLoaded',init);