'use strict';
function makeTournament(edition){const r=RNG(`${career.seed}|BRACKET|${edition}`),ids=shuffle(r,[...career.fieldIds]);const roster={};for(const id of ids){if(id===player.id){roster[id]=deepClone(player);continue}if(friendPlayer&&id===friendPlayer.id){roster[id]=deepClone(friendPlayer);continue}const p=careerParticipant(id);if(p)roster[id]=participantForYear(p,edition)}const matches=[];for(let i=0;i<16;i+=2)matches.push({aId:ids[i],bId:ids[i+1],result:null,recorded:false});return{edition,roster,rounds:[matches],bronze:null,champId:null,runnerId:null,thirdId:null,userExit:null,completed:false}}
function tp(t,id){if(!id)return null;if(t.roster&&Object.prototype.hasOwnProperty.call(t.roster,id))return t.roster[id];return careerParticipant(id)}
function simulateStoredMatch(t,m,roundIndex,matchIndex){if(m.result)return m.result;const a=tp(t,m.aId),b=tp(t,m.bId),res=simulateGame(a,b,`${career.seed}|E${t.edition}|R${roundIndex}|M${matchIndex}`);m.result=res;if(!m.recorded){statMatch(a,b,res);m.recorded=true}return res}
function matchWinnerId(m){return m?.result?.winner?.id||null}
function matchLoserId(m){if(!m?.result||!m.aId||!m.bId||m.result.status==='dq_both')return null;if(!m.result.winner)return null;return m.result.winner.id===m.aId?m.bId:m.aId}
function ensureRound(t,ri){if(t.rounds[ri])return t.rounds[ri];const prev=t.rounds[ri-1];const arr=[];for(let i=0;i<prev.length;i+=2)arr.push({aId:matchWinnerId(prev[i]),bId:matchWinnerId(prev[i+1]),result:null,recorded:false});t.rounds[ri]=arr;return arr}
function simulateNonUserInRound(t,ri){const round=ensureRound(t,ri);round.forEach((m,i)=>{if(m.aId===player.id||m.bId===player.id)return;simulateStoredMatch(t,m,ri,i)})}
function locateUserMatch(t,ri){const round=ensureRound(t,ri);return round.findIndex(m=>m.aId===player.id||m.bId===player.id)}
function allRoundDone(t,ri){return ensureRound(t,ri).every(m=>m.result)}
function setupAfterSemis(t){const semis=ensureRound(t,2);if(!semis.every(m=>m.result))return;ensureRound(t,3);if(!t.bronze)t.bronze={aId:matchLoserId(semis[0]),bId:matchLoserId(semis[1]),result:null,recorded:false}}
function simulateRest(t,startRound=0){for(let ri=startRound;ri<4;ri++){const round=ensureRound(t,ri);for(let i=0;i<round.length;i++)simulateStoredMatch(t,round[i],ri,i);if(ri===2)setupAfterSemis(t)}setupAfterSemis(t);if(t.bronze&&!t.bronze.result){const res=simulateGame(tp(t,t.bronze.aId),tp(t,t.bronze.bId),`${career.seed}|E${t.edition}|BRONZE`);t.bronze.result=res;if(!t.bronze.recorded){statMatch(tp(t,t.bronze.aId),tp(t,t.bronze.bId),res);t.bronze.recorded=true}}finalizePodium(t)}
function finalizePodium(t){const final=ensureRound(t,3)[0];if(final?.result?.winner){t.champId=final.result.winner.id;t.runnerId=matchLoserId(final)}else{t.champId=null;t.runnerId=null}t.thirdId=t.bronze?.result?.winner?.id||null;t.completed=true}
function placementInTournament(t,id){if(t.champId===id)return 1;if(t.runnerId===id)return 2;if(t.thirdId===id)return 3;if(t.userExit&&id===player.id)return t.userExit;for(let ri=0;ri<t.rounds.length;ri++){const m=t.rounds[ri].find(x=>x.aId===id||x.bId===id);if(m?.result&&m.result.winner?.id!==id){if(ri===2)return 4;if(ri===1)return'8强';if(ri===0)return'16强'}}return'未参赛'}

function startEdition(){career.currentTournament=makeTournament(career.edition);saveCareer();renderCareerHeader();renderBracket();prepareUserRound(0)}
function prepareUserRound(ri){const t=career.currentTournament;simulateNonUserInRound(t,ri);if(ri===2)setupAfterSemis(t);const idx=locateUserMatch(t,ri);if(idx<0){simulateRest(t,ri);finalizeEdition();return}const m=ensureRound(t,ri)[idx];if((!m.aId||!m.bId)){const res=simulateStoredMatch(t,m,ri,idx);if(res.winner?.id===player.id){if(ri===3){simulateRest(t,ri);finalizeEdition()}else prepareUserRound(ri+1)}else{simulateRest(t,ri);finalizeEdition()}return}const oppId=m.aId===player.id?m.bId:m.aId,opp=tp(t,oppId),prior=deepClone(h2hFor(opp.id));career.focus={roundIndex:ri,matchIndex:idx,oppId,priorH:prior};saveCareer();showPregame(opp,ROUND_NAMES[ri])}
async function playFocusedMatch(){const t=career.currentTournament,f=career.focus,m=ensureRound(t,f.roundIndex)[f.matchIndex],a=tp(t,m.aId),b=tp(t,m.bId);const res=simulateStoredMatch(t,m,f.roundIndex,f.matchIndex);const opp=tp(t,f.oppId);await playLiveMatch(a,b,res);applyMatchConsequences(res,opp,ROUND_NAMES[f.roundIndex]);recordH2H(opp,ROUND_NAMES[f.roundIndex],res);career.matchLog.push({edition:career.edition,age:career.age,round:ROUND_NAMES[f.roundIndex],oppId:opp.id,opp:opp.name,status:res.status,win:res.winner?.id===player.id,score:res.score});saveCareer();showFocusedResult(opp,res,f.priorH,ROUND_NAMES[f.roundIndex])}
function applyMatchConsequences(res,opp,roundName){if(res.status==='dq_both'){career.health=clamp(career.health-2,35,100);career.currentTournament.userExit='驱逐';career.injuries.push({age:career.age,type:'场上冲突驱逐',impact:2,round:roundName,opp:opp.name});return}if(res.status==='season_injury'){career.currentTournament.userExit='伤退';const eff=res.injury?.effect||{health:-8};career.health=clamp(career.health+(eff.health||0),25,100);for(const k of ATTR_KEYS)if(eff[k])player.a[k]=clamp(player.a[k]+eff[k],45,99);career.injuries.push({age:career.age,type:res.injury?.type||'严重伤病',impact:Math.abs(eff.health||8),round:roundName,opp:opp.name})}}
function continueAfterFocusedResult(){const t=career.currentTournament,f=career.focus,m=ensureRound(t,f.roundIndex)[f.matchIndex],res=m.result;const win=res.winner?.id===player.id;if(res.status==='dq_both'||res.status==='season_injury'){simulateRest(t,f.roundIndex+1);finalizeEdition();return}if(!win){if(f.roundIndex===2){setupAfterSemis(t);prepareBronze()}else{simulateRest(t,f.roundIndex+1);finalizeEdition()}return}if(f.roundIndex===3){simulateRest(t,3);finalizeEdition();return}prepareUserRound(f.roundIndex+1)}
function prepareBronze(){const t=career.currentTournament;setupAfterSemis(t);if(!t.bronze||(!t.bronze.aId&&!t.bronze.bId)){simulateRest(t,3);finalizeEdition();return}if(t.bronze.aId!==player.id&&t.bronze.bId!==player.id){simulateRest(t,3);finalizeEdition();return}const oppId=t.bronze.aId===player.id?t.bronze.bId:t.bronze.aId;if(!oppId){const res=simulateGame(tp(t,t.bronze.aId),tp(t,t.bronze.bId),`${career.seed}|E${t.edition}|BRONZE`);t.bronze.result=res;finalizePodium(t);finalizeEdition();return}const opp=tp(t,oppId),prior=deepClone(h2hFor(opp.id));career.focus={roundIndex:'bronze',matchIndex:0,oppId,priorH:prior};showPregame(opp,'季军赛')}
async function playFocusedBronze(){const t=career.currentTournament,opp=tp(t,career.focus.oppId),a=tp(t,t.bronze.aId),b=tp(t,t.bronze.bId);if(!t.bronze.result){t.bronze.result=simulateGame(a,b,`${career.seed}|E${t.edition}|BRONZE`);statMatch(a,b,t.bronze.result);t.bronze.recorded=true}const res=t.bronze.result;await playLiveMatch(a,b,res);applyMatchConsequences(res,opp,'季军赛');recordH2H(opp,'季军赛',res);career.matchLog.push({edition:career.edition,age:career.age,round:'季军赛',oppId:opp.id,opp:opp.name,status:res.status,win:res.winner?.id===player.id,score:res.score});saveCareer();showFocusedResult(opp,res,career.focus.priorH,'季军赛',true)}
function continueAfterBronze(){const t=career.currentTournament;simulateRest(t,3);finalizeEdition()}

function finalizeEdition(){const t=career.currentTournament;if(!t.completed)simulateRest(t,0);finalizePodium(t);award(t.champId,1);award(t.runnerId,2);award(t.thirdId,3);const place=placementInTournament(t,player.id),entry={edition:career.edition,age:career.age,place,champId:t.champId,champ:careerParticipant(t.champId)?.name||'空缺',runnerId:t.runnerId,runner:careerParticipant(t.runnerId)?.name||'空缺',thirdId:t.thirdId,third:careerParticipant(t.thirdId)?.name||'空缺',health:Math.round(career.health)};career.history.push(entry);saveCareer();renderBracket();showEditionSummary(entry)}

function naturalAging(nextAge){const r=RNG(`${career.seed}|AGING|${nextAge}`),delta={};if(nextAge<=21){for(const k of shuffle(r,ATTR_KEYS).slice(0,5))delta[k]=(r()*.9+.3)}else if(nextAge<=26){for(const k of shuffle(r,ATTR_KEYS).slice(0,4))delta[k]=(r()*.6+.05)}else if(nextAge<=29){for(const k of shuffle(r,ATTR_KEYS).slice(0,4))delta[k]=(r()-.52)*.7}else{delta.speed=-(r()*.8+.35);delta.dunk=-(r()*.9+.3);delta.finish=-(r()*.45);delta.clutch=r()*.35;delta.strength=(r()-.35)*.35}if(career.health<75){delta.speed=(delta.speed||0)-.35;delta.dunk=(delta.dunk||0)-.35}for(const [k,v] of Object.entries(delta))player.a[k]=clamp(player.a[k]+v,45,99);career.health=clamp(career.health+(nextAge<28?rint(r,4,8):rint(r,2,6)),25,100);return delta}
function weakestAttrs(){return [...ATTR_KEYS].sort((a,b)=>player.a[a]-player.a[b]).slice(0,3)}
function makeOffseasonChoices(targetAge){const r=RNG(`${career.seed}|OFFSEASON|${targetAge}`),choices=[];const weak=weakestAttrs(),mentor=pick(r,MENTORS);choices.push({id:'mentor-'+mentor.id,title:mentor.name,desc:mentor.desc,delta:mentor.delta,style:mentor.style,mentor:mentor.name});if(career.health<82||career.injuries.at(-1)?.age===career.age)choices.push({id:'recovery',title:'把整个夏天交给康复团队',desc:'身体状态大幅恢复，但技术增长很少。',delta:{},health:16,note:'康复优先'});else choices.push({id:'body',title:'力量与爆发力周期',desc:'强化力量、终结、扣篮；体型变重后速度可能略微下降。',delta:{strength:1.6,finish:.9,dunk:1.1,speed:-.25},health:3,note:'身体强化'});const focus=weak[0];choices.push({id:'weakness',title:`补最明显的短板：${ATTR_LABEL[focus]}`,desc:`针对当前最弱项做专项训练，${ATTR_LABEL[focus]}提升明显，同时带动相邻能力。`,delta:{[focus]:2.0,[weak[1]]:.6},note:`补强${ATTR_LABEL[focus]}`});if(career.medals.gold===0&&career.edition>=3)choices.push({id:'pressure',title:'公开宣布：下一届只谈冠军',desc:'关键球和侵略性上升，但下一届手感波动也会更大。',delta:{clutch:1.2,finish:.5},flag:'publicPressure',note:'公开冲冠'});else if(career.history.at(-1)?.place===1)choices.push({id:'defend',title:'不庆祝，直接准备卫冕',desc:'关键球、外防小幅提高；性格对白会更像卫冕者。',delta:{clutch:.8,perimeter:.7},flag:'defendingMindset',note:'卫冕模式'});else choices.push({id:'shoot',title:'投篮实验室',desc:'三分和中距离同步提升，逐渐减少纯身体冲击。',delta:{three:1.4,mid:1.1,handle:.35},style:{three:.08,mid:.06,drive:-.03},note:'投射强化'});if(targetAge===19){const first=career.history[0]?.place;choices.push(first===1?{id:'rookie-story',title:'首冠之后拒绝庆功宴',desc:'第一年就夺冠让外界迅速抬高期待。你选择把庆功夜改成训练夜，关键球与防守小幅提升。',delta:{clutch:.9,perimeter:.6},flag:'rookieCold',note:'首冠后保持冷处理'}:{id:'rookie-story',title:'把第一届的结果贴在训练馆门口',desc:'无论首年走到哪一步，你决定整个夏天每天进门都先看一眼那张签表。控球、关键球和防守一起小幅提升。',delta:{handle:.7,clutch:.8,perimeter:.5},flag:'rookieMemory',note:'把首年结果变成训练动力'});}return shuffle(r,choices).slice(0,4)}
function applyOffseasonChoice(choice,targetAge){const before=deepClone(player.a);for(const [k,v] of Object.entries(choice.delta||{}))player.a[k]=clamp(player.a[k]+v,45,99);for(const [k,v] of Object.entries(choice.style||{}))player.style[k]=clamp((player.style[k]||0)+v,-.25,.45);if(choice.health)career.health=clamp(career.health+choice.health,25,100);if(choice.mentor){player.mentorHistory.push({age:targetAge,name:choice.mentor});career.styleNotes.push(`${targetAge}岁 ${choice.mentor}`)}if(choice.flag)career[choice.flag]=true;career.lastOffseason={targetAge,choice:choice.title,before,after:deepClone(player.a),note:choice.note||choice.title};saveCareer();return before}

function autoTournamentEdition(edition,playerInactive=true){const r=RNG(`${career.seed}|BRACKET|${edition}`),ids=shuffle(r,[...career.fieldIds]);const roster={};for(const id of ids){if(id===player.id&&playerInactive){roster[id]=null;continue}const p=careerParticipant(id);if(p)roster[id]=participantForYear(p,edition)}let round=[];for(let i=0;i<16;i+=2)round.push({aId:ids[i],bId:ids[i+1],result:null,recorded:false});const t={edition,roster,rounds:[round],bronze:null,completed:false};for(let ri=0;ri<4;ri++){ensureRound(t,ri);for(let i=0;i<t.rounds[ri].length;i++)simulateStoredMatch(t,t.rounds[ri][i],ri,i);if(ri===2)setupAfterSemis(t)}setupAfterSemis(t);if(t.bronze){t.bronze.result=simulateGame(tp(t,t.bronze.aId),tp(t,t.bronze.bId),`${career.seed}|E${edition}|BRONZE`);statMatch(tp(t,t.bronze.aId),tp(t,t.bronze.bId),t.bronze.result)}finalizePodium(t);award(t.champId,1);award(t.runnerId,2);award(t.thirdId,3);return{edition,champId:t.champId,runnerId:t.runnerId,thirdId:t.thirdId}}
function retireNow(retireAge){career.retired=true;career.retiredAge=retireAge;career.futureResults=[];for(let e=career.edition+1;e<=career.totalEditions;e++)career.futureResults.push(autoTournamentEdition(e,true));career.completed=true;saveCareer();finishCareer()}
function finishAfter15(){career.completed=true;career.retiredAge=career.retiredAge||career.age;saveCareer();finishCareer()}

function rankingRows(){return fieldPlayers().map(p=>{const s=career.stats[p.id]||{},pts=career.points[p.id]||0,score=pts+(s.wins||0)*.08-(s.dq||0)*.15;return{id:p.id,name:p.name,pos:p.pos,pts,score,gold:s.gold||0,silver:s.silver||0,bronze:s.bronze||0,wins:s.wins||0,dq:s.dq||0}}).sort((a,b)=>b.score-a.score||b.gold-a.gold||b.wins-a.wins)}
function mostFacedOpponent(){const arr=Object.entries(career.h2h).map(([id,h])=>({id,h,p:careerParticipant(id)})).filter(x=>x.p).sort((a,b)=>b.h.meetings-a.h.meetings);return arr[0]||null}
function biggestWin(){const icons=['jordan','kobe','lebron','curry','durant','shaq','iverson','griffin','edwards','magic','hakeem'];return career.matchLog.filter(x=>x.win&&icons.includes(x.oppId)).sort((a,b)=>icons.indexOf(a.oppId)-icons.indexOf(b.oppId))[0]||career.matchLog.find(x=>x.win)||null}
function makeCareerNarrative(rank){const myRank=rank.findIndex(x=>x.id===player.id)+1,firstGold=career.history.find(x=>x.place===1),rival=mostFacedOpponent(),big=biggestWin(),inj=career.injuries.sort((a,b)=>b.impact-a.impact)[0];const persona=getPersonality(player),mentors=player.mentorHistory?.map(x=>x.name.replace('师从 ','').replace('跟 ','')).slice(-3)||[];let p1=`18岁那年，#${player.number} ${player.name}第一次走进这项只办15届的街头赛事。那一届开始前，没有人知道这套由${persona.name.split('｜')[1]||'独特'}性格驱动的打法会走到哪里；大家只知道，他要和同一批15个名字反复见面，直到这条街自己给出排名。`;
 let p2;if(firstGold)p2=`真正改变叙事的是${firstGold.age}岁。那一年他第一次把冠军拿到手里。从那以后，对手赛前谈论他的方式变了：他不再只是签表里“那个自建球员”，而是一个已经证明自己能走完四轮的人。`;else p2=`冠军始终没有轻易落到他手里。也正因为如此，这段生涯没有被写成一路碾压的爽文：每一次接近领奖台、每一次被熟悉的对手挡住，都在逼他换一种解法。`;
 let p3=rival?`这15届里，最有连续性的章节属于${rival.p.name}。双方一共碰了${rival.h.meetings}次，${player.name}${rival.h.wins}胜${rival.h.losses}负。到了后面，他们赛前已经很少需要自我介绍；上一次谁赢、最后一球怎么处理，都会直接成为下一次开场对白的一部分。`:'有些对手只见过一次，有些名字则总差一个签位。固定参赛池让每一届都有记忆，却没有保证任何一组宿敌一定发生。';
 let p4=big?`如果要挑一场最能留在集锦里的胜利，那是${big.age}岁${big.round}击败${big.opp}。那场球没有替他赢下整个生涯，却给后面的每个对手一个很明确的信息：抽到这个签位，不能按“中上游自建球员”来准备。`:`他的履历里没有一场被单独神化的巨人杀手时刻，分量更多来自长期稳定地留在竞争中。`;
 let p5=inj?`当然，街头生涯从来不只往上走。${inj.age}岁对阵${inj.opp}时的${inj.type}是最明显的一次转折，身体状态从那以后不再只是一个数字。`:'他的身体没有遭遇决定性的重创，这让技术变化而不是康复成为生涯后半程的主线。';if(mentors.length)p5+=` 休赛期里，他先后把${mentors.join('、')}的一部分方法揉进自己的比赛，最后的打法已经和18岁开档时明显不同。`;
 let close;if(career.medals.gold>=4)close=`最终，他以${career.medals.gold}冠、${career.medals.silver}亚、${career.medals.bronze}季和历史第${myRank}名离开。最好的那些年份里，火把确实就在他的手中；而真正让人记住他的，不只是火把亮了多久，而是同一批对手十五次重新排好签表后，他依然一次次走回球场中央。`;else if(career.medals.gold>0)close=`最终排名第${myRank}。他没有把这项赛事变成自己的私人领地，但他真正举起过冠军，也真正经历过冠军之后所有人提高针对性的日子。那更像一段完整职业生涯，而不是一串随机比分。`;else close=`最终排名第${myRank}。他没有冠军，这会永远留在履历最显眼的位置；但没有冠军并不意味着没有故事。固定对手、伤病、训练与一次次重逢，让他的名字仍然在这15届赛事里留下了清晰轨迹。`;return[p1,p2,p3,p4,p5,close].map(x=>`<p>${x}</p>`).join('')}
