'use strict';
function scoreSkill(p,action,opp,late=false){const a=p.a,d=opp.a;let off=80,def=80;if(action==='three'){off=a.three*.8+a.handle*.12+a.clutch*(late?.08:.02);def=d.perimeter*.8+d.speed*.12+d.clutch*.03}else if(action==='mid'){off=a.mid*.72+a.handle*.16+a.clutch*(late?.1:.03);def=d.perimeter*.65+d.speed*.1+d.strength*.08+d.clutch*.03}else if(action==='drive'){off=a.finish*.48+a.dunk*.16+a.speed*.2+a.handle*.12;def=d.interior*.45+d.perimeter*.22+d.strength*.18+d.speed*.1}else{off=a.finish*.35+a.strength*.3+a.mid*.12+a.handle*.08;def=d.interior*.45+d.strength*.3+d.rebound*.08}return off-def}
function chooseAction(p,opp,r){const a=p.a,size=(p.h||195)-(opp.h||195),spd=a.speed-(opp.a.speed||80),str=a.strength-(opp.a.strength||80),sty=p.style||{};let w={three:Math.max(8,a.three-68)+(sty.three||0)*100,mid:Math.max(8,a.mid-70)+(sty.mid||0)*100,drive:Math.max(8,(a.finish+a.dunk)/2-68)+Math.max(0,spd)*1.2+(sty.drive||0)*100,post:Math.max(4,a.strength-75)+Math.max(0,size)*1.6+Math.max(0,str)*.8+(sty.post||0)*100};if(positionGroup(p.pos)==='big')w.post*=1.4;if(positionGroup(p.pos)==='guard')w.three*=1.15;for(const k in w)w[k]=Math.max(2,w[k]);const sum=Object.values(w).reduce((s,x)=>s+x,0);let x=r()*sum;for(const k of ['three','mid','drive','post']){x-=w[k];if(x<=0)return k}return'drive'}
function actionText(p,opp,action,made,pts,turnover=false){const verbs={three:['外线突然拔起','拉到弧顶外一步','连续运球后后撤到三分线外'],mid:['急停在肘区','横移一步进入中距离','背身转身后停在罚球线附近'],drive:['第一步直接压向篮下','变向后冲进油漆区','借速度抢到半个身位'],post:['把人压进低位','背身靠了两下','用力量把位置顶到禁区']};const arr=verbs[action],v=arr[hash32(p.id+opp.id+action+String(pts))%arr.length];if(turnover)return`${p.name}${v}，但${opp.name}把球切掉，球权交换。`;if(made)return`${p.name}${v}，出手命中，拿到${pts}分。`;return`${p.name}${v}，出手偏出。`}
function specialFlavor(p,opp,action,made,r){if(p.id==='griffin'&&action==='drive'&&made&&r()<.28)return{kind:'event',text:'💥 格里芬突然抓到一步起跳空间，直接从防守头顶完成一记夸张隔扣。全场先静了一瞬，随后炸开——这是镜头事件，不额外改变比分。'};if(p.id==='curry'&&action==='three'&&made&&r()<.22)return{kind:'event',text:'🎯 Curry 这球离三分线还有明显距离，场边已经有人提前转身。球进的一刻，整个球场开始起哄。'};if(p.id==='shaq'&&action==='post'&&made&&r()<.2)return{kind:'event',text:'🧱 Shaq 这一靠把篮架都撞得发响，工作人员盯了两秒篮筐才示意继续。'};if(p.id==='rodman'&&!made&&r()<.18)return{kind:'event',text:'🌀 Rodman 直接扑出边线去救一个几乎不可能的球，场边椅子倒了一排，比赛停了几秒才恢复。'};if(p.id==='jokic'&&made&&r()<.15)return{kind:'event',text:'🎭 Jokic 看起来像没发力，却用一个完全反直觉的角度把球送进。场边有人笑着摇头。'};if(p.id==='westbrook'&&action==='drive'&&made&&r()<.18)return{kind:'event',text:'⚡ Westbrook 落地后冲着场边怒吼，下一回合的情绪明显被他抬高了一档。'};return null}
function fightProbability(a,b){const ta=getPersonality(a).temper||0,tb=getPersonality(b).temper||0;let p=Math.max(0,(ta+tb-6))*.008;const h=a.id===player?.id?h2hFor(b.id):b.id===player?.id?h2hFor(a.id):null;if(h?.meetings>=3)p+=.018;if([a.id,b.id].some(x=>['draymond','kg','metta','patbev'].includes(x)))p+=.012;return clamp(p,0,.09)}
function seasonInjuryProbability(custom){if(!career||custom.id!==player?.id)return 0;let p=.006+Math.max(0,career.age-26)*.003+Math.max(0,85-career.health)*.0012;return clamp(p,.004,.055)}
function simulateGame(a0,b0,seed,live=false){if(!a0&&!b0)return{winner:null,status:'empty',score:[0,0],plays:[],notes:[]};if(!a0)return{winner:b0,status:'bye',score:[0,0],plays:[{kind:'event',text:`${b0.name}轮空晋级。`}],notes:[]};if(!b0)return{winner:a0,status:'bye',score:[0,0],plays:[{kind:'event',text:`${a0.name}轮空晋级。`}],notes:[]};const a=deepClone(a0),b=deepClone(b0),r=RNG(seed),plays=[],notes=[matchupSentence(a,b)],score=[0,0];let poss=r()<.5?0:1,guard=0,minorPenalty={};const fightAt=r()<fightProbability(a,b)?rint(r,5,11):-1;let injuryAt=-1,injuryType=null,injuryEffect=null;
  const userSide=a.id===player?.id?0:b.id===player?.id?1:-1;if(userSide>=0){const opp=userSide===0?b:a;if(opp.id==='zaza'&&r()<.075){injuryAt=rint(r,4,9);injuryType='落脚点争议导致严重脚踝伤';injuryEffect={health:-14,speed:-1.6,dunk:-1.4,finish:-.8}}else if(r()<seasonInjuryProbability(player)){injuryAt=rint(r,6,13);injuryType=r()<.35?'膝部扭伤':'严重脚踝扭伤';injuryEffect={health:-rint(r,7,12),speed:-.7,dunk:-.6}}}
  while(guard++<70){const offense=poss===0?a:b,defense=poss===0?b:a,i=poss,late=Math.max(score[0],score[1])>=8;const action=chooseAction(offense,defense,r);const handle=offense.a.handle||80,pressure=(defense.a.perimeter||80)+(action==='post'?(defense.a.strength||80)*.3:0);let tov=clamp(.075+(pressure-handle)*.0022,.025,.22);if(minorPenalty[offense.id])tov+=.02;if(r()<tov){plays.push({kind:'play',off:i,action:'turnover',made:false,points:0,score:[...score],text:actionText(offense,defense,action,false,0,true)});poss=1-poss}else{let diff=scoreSkill(offense,action,defense,late),p=action==='three'?.38:action==='mid'?.46:action==='drive'?.53:.52;p+=diff*.0075;if(late)p+=(offense.a.clutch-defense.a.clutch)*.0025;if(minorPenalty[offense.id])p-=.045;p=clamp(p,.16,.79);const made=r()<p,pts=made?(action==='three'?2:1):0;if(made)score[i]+=pts;const play={kind:'play',off:i,action,made,points:pts,score:[...score],text:actionText(offense,defense,action,made,pts,false)};plays.push(play);const flav=specialFlavor(offense,defense,action,made,r);if(flav)plays.push({...flav,score:[...score],off:i});if(!made){const orb=clamp(.13+((offense.a.rebound||75)-(defense.a.rebound||75))*.004,.04,.35);if(r()<orb){plays.push({kind:'play',off:i,action:'rebound',made:false,points:0,score:[...score],text:`${offense.name}抢到进攻篮板，球权没有交换。`})}else poss=1-poss}else poss=1-poss}
    const realPoss=plays.filter(x=>x.kind==='play').length;if(realPoss===fightAt){plays.push({kind:'danger',event:'fight',score:[...score],text:`⚠️ 一次身体接触后双方谁都没有退。推搡迅速升级，队友和工作人员冲进场内把人拉开。两人被同时驱逐，这场没有胜者。`});return{winner:null,status:'dq_both',score,plays,notes}}
    if(realPoss===injuryAt&&userSide>=0){const custom=userSide===0?a:b,opp=userSide===0?b:a;let text;if(opp.id==='zaza')text='🚑 一次争抢后的落脚点冲突引发巨大争议。你的脚踝明显无法继续承重；在这个架空游戏事件里，这一届直接报销，身体状态也会留下长期影响。';else text=`🚑 ${custom.name}在落地时出现${injuryType}，尝试活动后仍无法继续。本届比赛提前结束。`;plays.push({kind:'danger',event:'injury',score:[...score],text});return{winner:opp,status:'season_injury',score,plays,notes,injury:{type:injuryType,effect:injuryEffect}}}
    const max=Math.max(score[0],score[1]),min=Math.min(score[0],score[1]);if((max>=11&&max-min>=2)||max>=15){const winner=score[0]>score[1]?a0:b0;return{winner,status:'final',score,plays,notes}}
  }
  const winner=score[0]>=score[1]?a0:b0;return{winner,status:'final',score,plays,notes}
}

function courtPosFor(action,off){const flip=off===0?1:-1;const base=off===0?45:55;if(action==='three')return{ox:base+flip*22,oy:72,dx:50+flip*8,dy:47};if(action==='mid')return{ox:base+flip*12,oy:49,dx:50+flip*4,dy:35};if(action==='drive')return{ox:50+flip*5,oy:27,dx:50,dy:22};if(action==='post')return{ox:50+flip*3,oy:22,dx:50-flip*2,dy:18};if(action==='rebound')return{ox:50+flip*5,oy:18,dx:50-flip*5,dy:20};return{ox:base,oy:70,dx:50,dy:45}}
function setDot(el,x,y){el.style.left=`calc(${x}% - 19px)`;el.style.top=`calc(${y}% - 19px)`}
function sleep(ms){return new Promise(res=>setTimeout(res,ms))}
async function playLiveMatch(a,b,res){$('storyCard').classList.add('hidden');$('resultCard').classList.add('hidden');$('liveCard').classList.remove('hidden');$('liveMatchTitle').textContent=`${a.name} vs ${b.name}`;$('scoreA').textContent=0;$('scoreB').textContent=0;$('liveLog').innerHTML='';$('dotA').querySelector('span').textContent=(a.name.split(' ').at(-1)||a.name).slice(0,3);$('dotB').querySelector('span').textContent=(b.name.split(' ').at(-1)||b.name).slice(0,3);setDot($('dotA'),38,78);setDot($('dotB'),55,48);let shown=[0,0];for(const p of res.plays){const delay=liveSpeed===2?115:230;if(p.kind==='play'){const pos=courtPosFor(p.action,p.off);const oe=p.off===0?$('dotA'):$('dotB'),de=p.off===0?$('dotB'):$('dotA');setDot(oe,pos.ox,pos.oy);setDot(de,pos.dx,pos.dy);$('ball').style.left=`${pos.ox}%`;$('ball').style.top=`${pos.oy}%`;await sleep(delay*.45);if(['three','mid','drive','post'].includes(p.action)){$('ball').style.left='50%';$('ball').style.top='10%'}await sleep(delay*.35)}else await sleep(delay*.45);if(p.score){shown=p.score;$('scoreA').textContent=shown[0];$('scoreB').textContent=shown[1]}const line=document.createElement('div');line.className='live-line '+(p.kind==='danger'?'danger':p.kind==='event'?'event':p.made?'score':'');line.textContent=p.text;$('liveLog').appendChild(line);$('liveLog').scrollTop=$('liveLog').scrollHeight;await sleep(delay*.35)}await sleep(liveSpeed===2?120:240);$('liveCard').classList.add('hidden')}
