'use strict';
let buildSelections={};
function initUI(){populateBuilder();wireUI();renderMenu();if(loadSaved())renderMenu()}
function wireUI(){
 $('newSoloBtn').onclick=()=>{clearCareer();player=null;friendPlayer=null;pendingMode='solo';resetBuilder(true);showScreen('build')};
 $('newMultiBtn').onclick=()=>{clearCareer();friendPlayer=null;player=loadLastPlayer();pendingMode='multi';renderMulti();showScreen('multi')};
 document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>showScreen('menu'));
 $('homeBtn').onclick=()=>{saveCareer();renderMenu();showScreen('menu')};
 $('lockBuildBtn').onclick=lockBuild;
 $('multiBuildBtn').onclick=()=>{pendingMode='multi';resetBuilder(false);showScreen('build')};
 $('loadFriendBtn').onclick=loadFriend;
 $('randomSeedBtn').onclick=()=>{$('sharedSeed').value=uid('STREET').slice(0,18)};
 $('startMultiBtn').onclick=startMulti;
 $('startCareerBtn').onclick=()=>{showScreen('career');startEdition()};
 $('startMatchBtn').onclick=()=>{if(career.focus?.roundIndex==='bronze')playFocusedBronze();else playFocusedMatch()};
 document.querySelectorAll('.speed-btn').forEach(b=>b.onclick=()=>{liveSpeed=+b.dataset.speed;document.querySelectorAll('.speed-btn').forEach(x=>x.classList.toggle('active',x===b))});
 $('retireHomeBtn').onclick=()=>{renderMenu();showScreen('menu')};$('newCareerFromRetire').onclick=()=>{clearCareer();player=null;friendPlayer=null;renderMenu();showScreen('menu')};
}
function renderMenu(){const box=$('continueBox');if(career){box.classList.remove('hidden');const done=career.completed;box.innerHTML=`<div class="title-row"><div><b>${done?'已完成生涯':'当前生涯'}</b><div class="muted">${player?.name||''} · ${done?'15届已结算':`${career.age}岁 · 第${career.edition}届`} · 固定16人名单</div></div><span class="pill">${career.seed}</span></div><button id="continueCareerBtn" class="secondary">${done?'查看最终榜单':'继续这条时间线'}</button>`;$('continueCareerBtn').onclick=resumeCareer}else box.classList.add('hidden')}
function resumeCareer(){if(career.completed){finishCareer();return}if(career.offseasonState){renderOffseason();return}showScreen('career');renderCareerHeader();renderBracket();renderHistory();const ui=career.uiState;if(ui?.type==='editionSummary'){const e=career.history.at(-1);showEditionSummary(e,true);return}if(ui?.type==='postmatch'&&career.focus){resumePostMatch();return}if(ui?.type==='pregame'&&career.focus){const t=career.currentTournament,opp=tp(t,career.focus.oppId);showPregame(opp,career.focus.roundIndex==='bronze'?'季军赛':ROUND_NAMES[career.focus.roundIndex]);return}if(career.currentTournament&&!career.currentTournament.completed){const ri=typeof career.focus?.roundIndex==='number'?career.focus.roundIndex:0;prepareUserRound(ri)}else startEdition()}

function populateBuilder(){const hs=[];for(let h=180;h<=216;h+=3)hs.push(h);$('pHeight').innerHTML=hs.map(h=>`<option value="${h}" ${h===195?'selected':''}>${h}cm</option>`).join('');const ws=[];for(let w=75;w<=125;w+=5)ws.push(w);$('pWeight').innerHTML=ws.map(w=>`<option value="${w}" ${w===95?'selected':''}>${w}kg</option>`).join('');$('pPersonality').innerHTML=Object.entries(PERSONALITIES).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join('');$('pPersonality').onchange=()=>{renderPersonality();renderBuildPreview()};['pName','pNumber','pPos','pHeight','pWeight'].forEach(id=>$(id).addEventListener(id==='pName'||id==='pNumber'?'input':'change',renderBuildPreview));resetBuilder(true)}
function resetBuilder(blankName=true){buildSelections={};for(const k of ATTR_KEYS){const names=SKILLS[k].tiers[3];buildSelections[k]={tier:3,template:names[0]}}if(blankName){$('pName').value='';$('pNumber').value=''}else if(player){$('pName').value=player.name||'';$('pNumber').value=player.number??'';$('pPos').value=player.pos||'PG';$('pHeight').value=String(player.h||195);$('pWeight').value=String(player.w||95);$('pPersonality').value=player.personality||'duncan'}renderSkillBuilder();renderPersonality();renderBuildPreview()}
function renderPersonality(){const v=PERSONALITIES[$('pPersonality').value];$('personalityText').innerHTML=`<b>${v.name}</b>：${v.tone} <span class="muted">这会影响对话、临场波动、冲突概率和故事线。</span>`}
function renderSkillBuilder(){const box=$('skillBuilder');box.innerHTML='';for(const k of ATTR_KEYS){const s=SKILLS[k],sel=buildSelections[k];const div=document.createElement('div');div.className='skill-card';div.innerHTML=`<div class="skill-top"><div class="skill-name"><b>${s.label}</b><small>${s.desc}</small></div><select class="template-select" data-k="${k}"></select><div class="tier-score">${sel.tier}</div></div><div class="tier-options">${[1,2,3,4,5].map(t=>`<button class="tier-btn ${t===sel.tier?'active':''}" data-k="${k}" data-tier="${t}">${t}分</button>`).join('')}</div><div class="template-names">${s.tiers[sel.tier].join(' · ')}</div>`;box.appendChild(div);const select=div.querySelector('.template-select');select.innerHTML=s.tiers[sel.tier].map(n=>`<option>${n}</option>`).join('');select.value=sel.template;select.onchange=e=>{buildSelections[k].template=e.target.value;renderBuildPreview()}}
 box.querySelectorAll('.tier-btn').forEach(b=>b.onclick=()=>{const k=b.dataset.k,t=+b.dataset.tier;buildSelections[k]={tier:t,template:SKILLS[k].tiers[t][0]};renderSkillBuilder();renderBuildPreview()});updateBudget()}
function updateBudget(){const used=skillCostFromBuild(buildSelections);$('budgetText').textContent=`${used} / ${BUILD_BUDGET}`;$('budgetText').style.color=used>BUILD_BUDGET?'var(--red)':'var(--text)';$('budgetFill').style.width=`${Math.min(100,used/BUILD_BUDGET*100)}%`;return used}
function buildDraft(){const name=$('pName').value.trim(),number=$('pNumber').value,pos=$('pPos').value,h=+$('pHeight').value,w=+$('pWeight').value,personality=$('pPersonality').value;if(!name||number===''||number<0||number>99)return null;return makePlayerFromBuild({name,number,pos,h,w,personality,build:buildSelections})}
function renderBuildPreview(){const used=updateBudget(),draft=buildDraft();if(!draft){$('buildPreview').innerHTML='<b>构建预览</b><p class="muted">先填写姓名和0–99号球衣号码。</p>';return}const comp=similarTemplates(draft);$('buildPreview').innerHTML=`<div class="title-row"><div><b>#${draft.number} ${draft.name}</b><div class="muted">${draft.pos} · ${draft.h}cm / ${draft.w}kg</div></div><b style="font-size:24px;color:var(--gold)">${streetOVR(draft).toFixed(1)}</b></div><div class="attr-grid" style="margin-top:10px">${ATTR_KEYS.map(k=>`<div class="attr-chip">${ATTR_LABEL[k]}<b>${Math.round(draft.a[k])}</b></div>`).join('')}</div><div class="template-compare">当前粗略上下限模板：<b>${comp.floor.name}</b> ← 你 → <b>${comp.ceiling.name}</b><br><span class="muted">这只是属性向量相似度，不代表生涯成就预测。</span></div>${used>BUILD_BUDGET?'<p style="color:var(--red)">预算超限，无法锁定。</p>':''}`}
function lockBuild(){const used=updateBudget(),draft=buildDraft();if(!draft){toast('姓名和球衣号码必须填写');return}if(used>BUILD_BUDGET){toast('天赋预算超限');return}player=draft;localStorage.setItem(BUILD_KEY,JSON.stringify(player));if(pendingMode==='multi'){renderMulti();showScreen('multi');return}const seed=newCareerSeed();initCareer('solo',seed);renderField();showScreen('field')}

function renderMulti(){const p=player||loadLastPlayer();if(p)player=p;$('multiSelf').innerHTML=player?`<div class="roster-card me"><b>#${player.number} ${player.name}</b><small>${player.pos} · 街球值 ${streetOVR(player).toFixed(1)}</small></div>`:'<p class="muted">还没有自己的球员。</p>';if(friendPlayer)$('friendPreview').innerHTML=`<div class="roster-card"><b>#${friendPlayer.number} ${friendPlayer.name}</b><small>${friendPlayer.pos} · 街球值 ${streetOVR(friendPlayer).toFixed(1)}</small></div>`}
function loadFriend(){try{const p=decodeCode($('friendCode').value,'SK5');if(!p?.a)throw new Error('无效角色');friendPlayer=p;renderMulti();toast('朋友角色已导入')}catch(e){toast('角色码读取失败') }}
function startMulti(){if(!player){toast('先创建自己的球员');return}if(!friendPlayer){toast('先导入朋友角色');return}const shared=$('sharedSeed').value.trim();if(!shared){toast('需要共同赛事码');return}const canonical=shared+'|'+[currentPlayerCode(),encodeCode(playerCodePayload(friendPlayer),'SK5')].sort().join('|');initCareer('multi',canonical);renderField();showScreen('field')}

function renderField(){const field=fieldPlayers();$('fieldSeedLabel').textContent=career.seed.slice(0,18);$('selectedField').innerHTML=field.map(p=>`<div class="roster-card ${p.id===player.id?'me':''}"><b>${p.id===player.id?'★ ':''}${p.name}</b><small>${p.pos} · ${Math.round(streetOVR(p))}${friendPlayer&&p.id===friendPlayer.id?' · 好友':''}</small></div>`).join('');$('candidatePool').innerHTML=NBA_POOL.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<span>${p.name} · ${p.pos}</span>`).join('');const pc=$('playerCodeBox');pc.classList.remove('hidden');pc.innerHTML=`<b>你的角色码</b><p class="muted">多人模式把它发给朋友。</p><textarea id="playerCodeText" readonly>${currentPlayerCode()}</textarea><button id="copyPlayerCodeBtn" class="secondary">复制角色码</button>`;$('copyPlayerCodeBtn').onclick=()=>copyText(currentPlayerCode())}

function renderCareerHeader(){$('editionLabel').textContent=`EDITION ${career.edition} / ${career.totalEditions}`;$('careerTitle').textContent=`${career.age}岁 · 第${career.edition}届路人王`;$('careerRecord').textContent=`${career.medals.gold}冠 · ${career.medals.silver}亚 · ${career.medals.bronze}季 · 固定16人池`;$('healthText').textContent=Math.round(career.health);$('careerAgeRange').textContent='18–32岁 · 共15届';renderHistory()}
function renderBracket(){const t=career.currentTournament;if(!t)return;const cols=[];for(let ri=0;ri<4;ri++){const round=t.rounds[ri];if(!round)continue;cols.push(`<div class="round-col"><div class="round-title">${ROUND_NAMES[ri]}</div>${round.map(m=>renderMatchBox(t,m)).join('')}</div>`)}$('bracket').innerHTML=cols.join('');$('stageLabel').textContent=career.focus?.roundIndex==='bronze'?'季军赛':typeof career.focus?.roundIndex==='number'?ROUND_NAMES[career.focus.roundIndex]:'赛事进行中';if(t.bronze)$('bronzeInfo').innerHTML=`<div class="card" style="margin-top:9px"><b>季军赛</b><div class="muted">${tp(t,t.bronze.aId)?.name||'待定'} vs ${tp(t,t.bronze.bId)?.name||'待定'} ${t.bronze.result?`· ${t.bronze.result.score.join(':')}`:''}</div></div>`;else $('bronzeInfo').innerHTML=''}
function renderMatchBox(t,m){const a=tp(t,m.aId),b=tp(t,m.bId),r=m.result,w=r?.winner?.id;return `<div class="match-box"><div class="match-line ${w===m.aId?'winner':''} ${m.aId===player.id?'me':''}"><span>${a?.name||'BYE'}</span><b>${r?r.score[0]:''}</b></div><div class="match-line ${w===m.bId?'winner':''} ${m.bId===player.id?'me':''}"><span>${b?.name||'BYE'}</span><b>${r?r.score[1]:''}</b></div>${r?.status==='dq_both'?'<div style="color:var(--red);font-size:10px">双方驱逐</div>':''}</div>`}
function showPregame(opp,roundName){showScreen('career');renderCareerHeader();renderBracket();$('liveCard').classList.add('hidden');$('resultCard').classList.add('hidden');$('storyCard').classList.remove('hidden');$('storyHeading').textContent=`${roundName} · ${opp.name}`;$('storyBody').innerHTML=pregameDialogue(opp,roundName);$('startMatchBtn').textContent=roundName==='季军赛'?'开始季军赛':'开始比赛';career.uiState={type:'pregame'};saveCareer()}
function showFocusedResult(opp,res,priorH,roundName,isBronze=false){$('storyCard').classList.add('hidden');$('resultCard').classList.remove('hidden');renderBracket();const win=res.winner?.id===player.id,headline=res.status==='dq_both'?'双方驱逐':res.status==='season_injury'?'伤病退赛':win?'晋级':'失利';$('matchResult').innerHTML=`<div class="result-banner ${win?'win':'lose'}"><b>${headline}</b><div class="score-big">${res.score[0]} : ${res.score[1]}</div></div>${postgameDialogue(opp,res,roundName,priorH)}`;$('continueBtn').textContent='继续';$('continueBtn').onclick=isBronze?continueAfterBronze:continueAfterFocusedResult;career.uiState={type:'postmatch',bronze:isBronze};saveCareer()}
function resumePostMatch(){const t=career.currentTournament,f=career.focus;if(!f)return;const opp=tp(t,f.oppId);let res;if(f.roundIndex==='bronze')res=t.bronze?.result;else res=t.rounds[f.roundIndex]?.[f.matchIndex]?.result;if(res)showFocusedResult(opp,res,f.priorH,f.roundIndex==='bronze'?'季军赛':ROUND_NAMES[f.roundIndex],f.roundIndex==='bronze');else showPregame(opp,f.roundIndex==='bronze'?'季军赛':ROUND_NAMES[f.roundIndex])}
function showEditionSummary(entry,resume=false){showScreen('career');$('storyCard').classList.add('hidden');$('liveCard').classList.add('hidden');$('resultCard').classList.remove('hidden');renderCareerHeader();renderBracket();const medal=entry.place===1?'🏆 冠军':entry.place===2?'🥈 亚军':entry.place===3?'🥉 季军':entry.place;$('matchResult').innerHTML=`<div class="result-banner ${entry.place===1?'win':''}"><b>${career.age}岁 · ${medal}</b></div><p class="story">本届冠军：<b>${entry.champ}</b>；亚军：${entry.runner}；季军：${entry.third}。</p><p class="muted">下一步进入休赛期：年龄、伤病和你的选择都会开始改变能力值。</p>`;$('continueBtn').textContent=career.edition>=15?'结算十五届历史榜':'进入休赛期';$('continueBtn').onclick=()=>career.edition>=15?finishAfter15():openOffseason();career.uiState={type:'editionSummary'};saveCareer()}
function renderHistory(){if(!career)return;$('historyList').innerHTML=career.history.slice().reverse().map(h=>`<div class="history-row"><b>${h.age}岁</b><span>冠军 ${h.champ}</span><span class="medal ${h.place===1?'gold':h.place===2?'silver':h.place===3?'bronze':''}">${typeof h.place==='number'?(h.place===1?'冠军':h.place===2?'亚军':h.place===3?'季军':'第4'):h.place}</span></div>`).join('')||'<p class="muted">第一届还没有结束。</p>'}

function openOffseason(){const target=career.age+1;if(!career.offseasonState||career.offseasonState.targetAge!==target){const natural=naturalAging(target);career.offseasonState={targetAge:target,natural,chosen:null};saveCareer()}renderOffseason()}
function renderOffseason(){showScreen('offseason');const o=career.offseasonState,target=o.targetAge;$('offseasonTitle').textContent=`${career.age} → ${target}岁 · 第${career.edition}届结束后的夏天`;const comp=similarTemplates(player);$('compText').textContent=`街球值 ${streetOVR(player).toFixed(1)}`;$('offseasonAttrs').innerHTML=ATTR_KEYS.map(k=>{const n=o.natural?.[k]||0;const c=o.chosen&&career.lastOffseason?.before?player.a[k]-career.lastOffseason.before[k]:0;const d=o.chosen?c:n;return `<div class="attr-chip">${ATTR_LABEL[k]}<b>${Math.round(player.a[k])}</b>${Math.abs(d)>.05?`<small class="${d>0?'attr-up':'attr-down'}">${d>0?'+':''}${d.toFixed(1)}</small>`:''}</div>`}).join('');$('templateCompare').innerHTML=`当前历史属性下限模板：<b>${comp.floor.name}</b>　·　上限模板：<b>${comp.ceiling.name}</b><br><span class="muted">随着训练、年龄和伤病，这两个模板会变化。</span>`;
 if(o.chosen){$('offseasonChoices').innerHTML=`<div class="info-strip"><b>你选择了：${o.chosen}</b><br>${career.lastOffseason?.note||''}。能力和打法已经更新。</div><button id="enterNextSeasonBtn" class="primary">进入${target}岁 · 第${career.edition+1}届</button>`;$('enterNextSeasonBtn').onclick=()=>{career.age=target;career.edition++;career.currentTournament=null;career.focus=null;career.offseasonState=null;career.uiState=null;saveCareer();showScreen('career');startEdition()}}else{const choices=makeOffseasonChoices(target);$('offseasonChoices').innerHTML=choices.map((c,i)=>`<button class="choice-btn" data-choice="${i}"><b>${c.title}</b><small>${c.desc}</small></button>`).join('');$('offseasonChoices').querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const c=choices[+b.dataset.choice];applyOffseasonChoice(c,target);career.offseasonState.chosen=c.title;saveCareer();renderOffseason()})}
 const rb=$('retireChoiceBox');if(target>=30&&!o.chosen){rb.classList.remove('hidden');rb.innerHTML=`<h3>${target}岁 · 是否现在退役？</h3><p class="muted">如果现在退役，你不再参加剩余赛事，但固定参赛池会继续把余下届数完整模拟完，再统一生成最终榜单。</p><button id="retireNowBtn" class="secondary">宣布退役 · 让世界继续模拟</button>`;$('retireNowBtn').onclick=()=>retireNow(target)}else rb.classList.add('hidden');career.uiState={type:'offseason'};saveCareer()}

function finishCareer(){showScreen('retire');const rank=rankingRows(),me=rank.find(x=>x.id===player.id),idx=rank.findIndex(x=>x.id===player.id)+1;$('legacySummary').innerHTML=`<div class="title-row"><div><span class="eyebrow">#${player.number} ${player.name}</span><h3>最终历史第 ${idx} 名</h3></div><b style="font-size:27px;color:var(--gold)">${me?.pts||0} pts</b></div><div class="attr-grid" style="margin-top:10px"><div class="attr-chip">冠军<b>${career.medals.gold}</b></div><div class="attr-chip">亚军<b>${career.medals.silver}</b></div><div class="attr-chip">季军<b>${career.medals.bronze}</b></div><div class="attr-chip">退役<b>${career.retiredAge||32}岁</b></div></div>${career.mode==='multi'?`<p class="muted">你和${friendPlayer.name}最终关系：${career.relationship.label} · 正面交手${career.relationship.meetings}次。</p>`:''}`;$('leaderboard').innerHTML=rank.map((x,i)=>`<div class="leader-row" style="${x.id===player.id?'background:#21180f':''}"><b>${i+1}</b><span><b>${x.name}</b><br><small class="muted">${x.gold}冠 ${x.silver}亚 ${x.bronze}季 · ${x.wins}胜${x.dq?' · '+x.dq+'次驱逐':''}</small></span><span class="gold">${x.pts}</span></div>`).join('');$('careerNarrative').innerHTML=makeCareerNarrative(rank);career.uiState={type:'retire'};saveCareer();renderMenu()}

document.addEventListener('DOMContentLoaded',initUI);
